### ISSUE TITLE
Debugging errors

### ISSUE THREAD

**Issue by snwfdhmp** [raulGX/go-shopping#4]
### You should not panic(err)

https://github.com/raulGX/go-shopping/blob/70d19c6f6137f2eea994c1b07c9bdec630463bd0/services/usermgmt/storage.go#L20-L41

Hey dude,

Just a friendly advice. You should not panic(err). You’d rather use [a package like this](https://github.com/snwfdhmp/errlog) for debugging your errors. Debug your code with :

1. Clear stack trace
2. Failing func call highlighting

<img width="999" alt="example" src="https://user-images.githubusercontent.com/23099246/53098953-11310c80-3525-11e9-8f6f-302791743cdf.png">

It’s way more easier then to debug.

Real better than panic-ing (in most case). You can still force exit if you need it.

I would be happy to get your feedbacks.

**Comment by raulGX** [comment]
thanks for the input :), I'll take a look at the package
